name: interactive_chart
description: An candle stick chart that supports pinch-to-zoom and panning.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
