name: interactive_chart
description: A candlestick chart that supports hand gestures such as pinch-to-zoom and panning.
version: 0.3.5
homepage: https://github.com/h65wang/flutter-interactive-chart

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
